In [ ]:
import pandas as pd
Dataset = pd.read_csv('student_marks.csv')

In [ ]:
#Print Top 5 rows of dataset
Dataset.head()

,Student_ID,Age,Gender,Study_Hours_Per_Week,Attendance_Rate,Sleep_Hours,Extracurricular_Activities,Internet_Access,Parental_Education,Previous_Score,Midterm_Score,Final_Score,Grade_Category
0,STU_0001,18,Male,39.725531,84.310085,7.306960,No,Yes,High School,82.667309,62.578709,80.677977,B
1,STU_0002,19,Male,34.799874,71.812059,6.629072,Yes,No,Associate,43.117966,61.791347,69.011077,D
2,STU_0003,17,Male,12.297868,65.464036,9.035082,No,Yes,Associate,91.584868,43.136120,48.908488,F
3,STU_0004,19,Male,37.570833,86.065590,4.964078,Yes,Yes,PhD,67.495199,81.132317,78.245319,C
4,STU_0005,19,Male,9.072824,89.543898,4.149830,No,Yes,High School,55.744965,66.172865,59.155277,F

In [ ]:
#Print Bottom 5 rows of dataset
Dataset.tail()

,Student_ID,Age,Gender,Study_Hours_Per_Week,Attendance_Rate,Sleep_Hours,Extracurricular_Activities,Internet_Access,Parental_Education,Previous_Score,Midterm_Score,Final_Score,Grade_Category
995,STU_0996,20,Male,28.007372,96.424229,8.322304,Yes,Yes,Bachelor,86.997406,64.107620,67.680849,D
996,STU_0997,19,Female,21.529863,80.394160,7.066682,Yes,Yes,Bachelor,97.767088,94.538854,69.918158,D
997,STU_0998,15,Female,35.805486,80.051026,7.625878,Yes,Yes,Associate,47.599352,78.275829,72.972018,C
998,STU_0999,15,Female,12.550924,62.009720,6.765390,No,Yes,Bachelor,65.237814,86.150192,65.988264,D
999,STU_1000,19,Female,28.723462,61.396462,8.972254,Yes,Yes,Bachelor,68.856496,62.113748,70.168771,C

In [ ]:
#Print Number of Rows and Columns in dataset
print('rows: ', Dataset.shape[0])
print('columns: ', Dataset.shape[1])

rows:  1000
columns:  13

In [ ]:
# Print/Determine all the null columns in dataset
Dataset.isnull().sum()

Student_ID                    0
Age                           0
Gender                        0
Study_Hours_Per_Week          0
Attendance_Rate               0
Sleep_Hours                   0
Extracurricular_Activities    0
Internet_Access               0
Parental_Education            0
Previous_Score                0
Midterm_Score                 0
Final_Score                   0
Grade_Category                0
dtype: int64

In [ ]:
# Print datatype of each column
Dataset.dtypes

Student_ID                        str
Age                             int64
Gender                            str
Study_Hours_Per_Week          float64
Attendance_Rate               float64
Sleep_Hours                   float64
Extracurricular_Activities        str
Internet_Access                   str
Parental_Education                str
Previous_Score                float64
Midterm_Score                 float64
Final_Score                   float64
Grade_Category                    str
dtype: object